---
title: "Multiplication Table"
type: "exercise"  # challenge, exercise, article, video
description: "Create a Multiplication Table with JavaScript Objects."
tags: "javascript, oop"
ignore:
- "multiplication-table.md"
